services:
  # Container 2: The Value Holder
  backend-service:
    build: .
    command: python backend.py
    # No ports exposed to the host, stays private

  # Container 1: The Value Printer
  frontend-service:
    build: .
    ports:
      - "7777:5000"
    depends_on:
      - backend-service
    command: python frontend.py
