services:
  # Container 2 (The one holding the value)
  backend-node:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install flask && python backend.py"

  # Container 1 (The one printing the value)
  frontend-node:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "7777:5000"
    command: sh -c "pip install flask requests && python frontend.py"
    depends_on:
      - backend-node
